version: "3.7"

services:
  dynamodb:
    image: localstack/localstack
    container_name: sqs
    hostname: sqs
    ports:
      - "4566:4566"
    volumes:
      - ./:/app
      - ./scripts:/docker-entrypoint-initaws.d
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=sa-east-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin

networks:
  default:
    external: true
    name: go_pubsub_sqs